version: 2

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/spec/example_app"
  schedule:
    interval: daily
    time: "08:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
